In [1]:
import numpy as np
import pandas as pd
from QSAR_Lab.Misvik_Bayeas_model.comparison import observe
from QSAR_Lab.Misvik_Bayeas_model.models import CombinationModel
from sklearn.metrics import (accuracy_score, confusion_matrix, precision_score,
                             recall_score)
from sklearn.naive_bayes import GaussianNB

In [2]:
my_model = GaussianNB()

# OX test

In [3]:
train_a549 = pd.read_excel("../Data/OX/a549_data.xlsx", sheet_name=1, index_col=0)
test_a549 = pd.read_excel("../Data/OX/a549_data.xlsx", sheet_name=2, index_col=0)
toxic_a549 = pd.read_excel("../Data/OX/a549_data.xlsx", sheet_name=3, index_col=0)

train_beas = pd.read_excel("../Data/OX/beas_data.xlsx", sheet_name=1, index_col=0)
test_beas = pd.read_excel("../Data/OX/beas_data.xlsx", sheet_name=2, index_col=0)
toxic_beas = pd.read_excel("../Data/OX/beas_data.xlsx", sheet_name=3, index_col=0)

train_hep = pd.read_excel("../Data/OX/hepg2_data.xlsx", sheet_name=1, index_col=0)
test_hep = pd.read_excel("../Data/OX/hepg2_data.xlsx", sheet_name=2, index_col=0)
toxic_hep = pd.read_excel("../Data/OX/hepg2_data.xlsx", sheet_name=3, index_col=0)

In [4]:
def observe2(obs):
    obs_val = obs.loc[:, "y"]
    obs_val.sort_index(inplace=True)
    return np.array(obs_val)

In [5]:
# Ilosc toksycznych NMs w zbiorze testowym
tox_in_test = 2

In [6]:
a549 = CombinationModel(my_model, train_a549,test_a549,toxic_a549,tox_in_test)
beas = CombinationModel(my_model, train_beas,test_beas,toxic_beas,tox_in_test)
hep = CombinationModel(my_model, train_hep,test_hep,toxic_hep,tox_in_test)

## Model A549 

In [7]:
obs = pd.read_excel("../Data/OX/a549_data.xlsx", index_col=0)
obs = observe2(obs)

pred = a549.predict_on_test
pred.sort_index(inplace=True)
pred = np.where(pred == "Toxic", 1, 0).flatten()

print(obs)
print(pred)

__predOnTest from func:  True
CREATE_DATA - number of sets: 6970
__predOnTest GLOBAL:  True
ELSE
[0 1 0 1 0 0 0 1 0 0 1 0 1 0 1 0 0 1 0 0 0]
[1 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0 0 1]


In [8]:
cm = confusion_matrix(obs, pred)
tn, fp, fn, tp = cm.ravel()

acc = accuracy_score(obs, pred)
prec = precision_score(obs, pred, average="binary")
rec = recall_score(obs, pred, average="binary")

print(f"Accuracy = {acc}")
print(f"Precison = {prec}")
print(f"Recall = {rec}")
print(f"tn = {tn}")
print(f"fp = {fp}")
print(f"fn = {fn}")
print(f"tp = {tp}")

Accuracy = 0.5714285714285714
Precison = 0.375
Recall = 0.42857142857142855
tn = 9
fp = 5
fn = 4
tp = 3


## Model BEAS

In [9]:
obs = pd.read_excel("../Data/OX/beas_data.xlsx", index_col=0)
obs = observe2(obs)

pred = beas.predict_on_test
pred.sort_index(inplace=True)
pred = np.where(pred == "Toxic", 1, 0).flatten()

print(obs)
print(pred)

__predOnTest from func:  True
CREATE_DATA - number of sets: 5358
__predOnTest GLOBAL:  True
ELSE
[1 0 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0]
[1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0]


In [10]:
cm = confusion_matrix(obs, pred)
tn, fp, fn, tp = cm.ravel()

acc = accuracy_score(obs, pred)
prec = precision_score(obs, pred, average="binary")
rec = recall_score(obs, pred, average="binary")

print(f"Accuracy = {acc}")
print(f"Precison = {prec}")
print(f"Recall = {rec}")
print(f"tn = {tn}")
print(f"fp = {fp}")
print(f"fn = {fn}")
print(f"tp = {tp}")

Accuracy = 0.9523809523809523
Precison = 1.0
Recall = 0.75
tn = 17
fp = 0
fn = 1
tp = 3


## Model HEP

In [11]:
obs = pd.read_excel("../Data/OX/hepg2_data.xlsx", index_col=0)
obs = observe2(obs)

pred = hep.predict_on_test
pred.sort_index(inplace=True)
pred = np.where(pred == "Toxic", 1, 0).flatten()

print(obs)
print(pred)

__predOnTest from func:  True
CREATE_DATA - number of sets: 10465
__predOnTest GLOBAL:  True
ELSE
[0 1 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0]
[0 0 0 1 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 0 0]


In [12]:
cm = confusion_matrix(obs, pred)
tn, fp, fn, tp = cm.ravel()

acc = accuracy_score(obs, pred)
prec = precision_score(obs, pred, average="binary")
rec = recall_score(obs, pred, average="binary")

print(f"Accuracy = {acc}")
print(f"Precison = {prec}")
print(f"Recall = {rec}")
print(f"tn = {tn}")
print(f"fp = {fp}")
print(f"fn = {fn}")
print(f"tp = {tp}")

Accuracy = 0.8571428571428571
Precison = 0.75
Recall = 0.6
tn = 15
fp = 1
fn = 2
tp = 3


# DNA test

In [13]:
train_a549 = pd.read_excel("../Data/DNA/a549_data.xlsx", sheet_name=1, index_col=0)
test_a549 = pd.read_excel("../Data/DNA/a549_data.xlsx", sheet_name=2, index_col=0)
toxic_a549 = pd.read_excel("../Data/DNA/a549_data.xlsx", sheet_name=3, index_col=0)

train_beas = pd.read_excel("../Data/DNA/beas_data.xlsx", sheet_name=1, index_col=0)
test_beas = pd.read_excel("../Data/DNA/beas_data.xlsx", sheet_name=2, index_col=0)
toxic_beas = pd.read_excel("../Data/DNA/beas_data.xlsx", sheet_name=3, index_col=0)

train_hep = pd.read_excel("../Data/DNA/hepg2_data.xlsx", sheet_name=1, index_col=0)
test_hep = pd.read_excel("../Data/DNA/hepg2_data.xlsx", sheet_name=2, index_col=0)
toxic_hep = pd.read_excel("../Data/DNA/hepg2_data.xlsx", sheet_name=3, index_col=0)

In [14]:
a549 = CombinationModel(my_model, train_a549,test_a549,toxic_a549,tox_in_test)
beas = CombinationModel(my_model, train_beas,test_beas,toxic_beas,tox_in_test)
hep = CombinationModel(my_model, train_hep,test_hep,toxic_hep,tox_in_test)

## Model A549 

In [15]:
obs = pd.read_excel("../Data/DNA/a549_data.xlsx", index_col=0)
obs = observe2(obs)

pred = a549.predict_on_test
pred.sort_index(inplace=True)
pred = np.where(pred == "Toxic", 1, 0).flatten()

print(obs)
print(pred)

__predOnTest from func:  True
CREATE_DATA - number of sets: 10914
__predOnTest GLOBAL:  True
ELSE
[0 1 1 1 0 0 0 1 0 0 0 0 1 1 1 0 1 1 0 1 0]
[0 0 1 0 1 0 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0]


In [16]:
cm = confusion_matrix(obs, pred)
tn, fp, fn, tp = cm.ravel()

acc = accuracy_score(obs, pred)
prec = precision_score(obs, pred, average="binary")
rec = recall_score(obs, pred, average="binary")

print(f"Accuracy = {acc}")
print(f"Precison = {prec}")
print(f"Recall = {rec}")
print(f"tn = {tn}")
print(f"fp = {fp}")
print(f"fn = {fn}")
print(f"tp = {tp}")

Accuracy = 0.47619047619047616
Precison = 0.4
Recall = 0.2
tn = 8
fp = 3
fn = 8
tp = 2


## Model BEAS

In [17]:
obs = pd.read_excel("../Data/DNA/beas_data.xlsx", index_col=0)
obs = observe2(obs)

pred = beas.predict_on_test
pred.sort_index(inplace=True)
pred = np.where(pred == "Toxic", 1, 0).flatten()

print(obs)
print(pred)

__predOnTest from func:  True
CREATE_DATA - number of sets: 8997
__predOnTest GLOBAL:  True
ELSE
[0 0 1 0 0 0 0 1 1 0 1 0 0 1 0 0 0 1 0 1 0]
[0 0 0 0 0 0 0 1 1 1 0 0 0 0 1 0 0 0 0 0 1]


In [18]:
cm = confusion_matrix(obs, pred)
tn, fp, fn, tp = cm.ravel()

acc = accuracy_score(obs, pred)
prec = precision_score(obs, pred, average="binary")
rec = recall_score(obs, pred, average="binary")

print(f"Accuracy = {acc}")
print(f"Precison = {prec}")
print(f"Recall = {rec}")
print(f"tn = {tn}")
print(f"fp = {fp}")
print(f"fn = {fn}")
print(f"tp = {tp}")

Accuracy = 0.6190476190476191
Precison = 0.4
Recall = 0.2857142857142857
tn = 11
fp = 3
fn = 5
tp = 2


## Model HEP

In [19]:
obs = pd.read_excel("../Data/DNA/hepg2_data.xlsx", index_col=0)
obs = observe2(obs)

pred = hep.predict_on_test
pred.sort_index(inplace=True)
pred = np.where(pred == "Toxic", 1, 0).flatten()

print(obs)
print(pred)

__predOnTest from func:  True
CREATE_DATA - number of sets: 8658
__predOnTest GLOBAL:  True
ELSE
[0 0 1 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 1 0]
[0 1 1 1 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0]


In [20]:
cm = confusion_matrix(obs, pred)
tn, fp, fn, tp = cm.ravel()

acc = accuracy_score(obs, pred)
prec = precision_score(obs, pred, average="binary")
rec = recall_score(obs, pred, average="binary")

print(f"Accuracy = {acc}")
print(f"Precison = {prec}")
print(f"Recall = {rec}")
print(f"tn = {tn}")
print(f"fp = {fp}")
print(f"fn = {fn}")
print(f"tp = {tp}")

Accuracy = 0.7619047619047619
Precison = 0.5
Recall = 0.6
tn = 13
fp = 3
fn = 2
tp = 3
